### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by hfiguiere** [flathub/uk.co.mangobrain.Infector#4]
The build is broken:

https://buildbot.flathub.org/#/builders/32/builds/100502

`infector.mangobrain.co.uk` doesn't resolve to download the source

**Comment by bbhtt** [comment]
This can be closed once https://github.com/flathub/uk.co.mangobrain.Infector/pull/5 is merged and the build is verified as 'published'. So I'm marking it as 'closes', will follow up to see if it is published.
